target_kinetis: ensure AP#0 is MEM_AP to avoid AttributeError
pyocd/pyOCD pull request #1019
Opened 2020-12-01 05:50 UTC by Hoohaha

Fixes #1015

Tested in my local with kl28z, make pyocd report no cores found

```
0007248:ERROR:target_kinetis:KL28x: bad MDM-AP IDR (is 0x02000000)
0017250:WARNING:target_kinetis:Forcing halt on connect in order to gain control of device
Exception while initing board: No cores were discovered!
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pyocd\commands\commander.py", line 206, in _post_connect
    self.session.open(init_board=not self.args.no_init)
  File "c:\python27\lib\site-packages\pyocd\core\session.py", line 461, in open
    self._board.init()
  File "c:\python27\lib\site-packages\pyocd\board\board.py", line 85, in init
    self.target.init()
  File "c:\python27\lib\site-packages\pyocd\core\soc_target.py", line 120, in init
    seq.invoke()
  File "c:\python27\lib\site-packages\pyocd\utility\sequencer.py", line 208, in invoke
    resultSequence = call()
  File "c:\python27\lib\site-packages\pyocd\coresight\coresight_target.py", line 220, in check_for_cores
    raise exceptions.DebugError("No cores were discovered!")
DebugError: No cores were discovered!
```

2020-12-01 17:54 UTC, flit requested changes
Changes look good.

Could you please add an NXP copyright below the existing Arm copyright in the two files you edited? (Recently I started trying to ensure that copyrights are correctly updated in all changes.)

2020-12-02 09:18 UTC, Hoohaha commented
copyright is added :smile:

2020-12-02 21:18 UTC, flit approved these changes

2020-12-02 21:18 UTC, flit commented
/morph test

2020-12-02 22:34 UTC, flit commented
/morph test

2020-12-06 21:23 UTC, merged