Fix/1553 rtt cb not found
pyocd/pyOCD pull request #1583
Opened 2023-07-10 06:46 UTC by tdasika

2023-07-11 18:17 UTC, flit requested changes
Just a couple small changes.

If you feel like it, please also add your copyright to the file's header comment.

2023-07-11 18:17 UTC, flit commented on pyocd/debug/rtt.py
> +            read_size = min(search_size, 8)
Reducing the read size will slow the search down noticeably. 
It's probably best to leave this at 32 for now.

(Really, the read size should be at least 512 or 1024 bytes for best performance, especially with HS USB probes. However, with large sizes like that you need to take into account the greater likelihood of running off the end of the memory region when not using the default RAM region.)

2023-07-11 18:17 UTC, flit commented on pyocd/debug/rtt.py
>              self._cb_search_size_words = size // 4
`self._cb_search_size_words` is set to the size in words here, but it's used as a byte count for `.read_memory_block8()` in the search routine.

So, please remove the divide by 4 and rename the attribute to `_cb_search_size_bytes`.

2023-07-30 21:22 UTC, flit commented
@tdasika Do you mind if I commit the requested changes to your branch so I can close out this PR? I'd like to make sure this fix is included in the next release. Thanks!

2023-07-31 03:54 UTC, tdasika commented
> @tdasika Do you mind if I commit the requested changes to your branch so I can close out this PR? I'd like to make sure this fix is included in the next release. Thanks!

@flit , I have addressed the requested changes.

2023-07-31 21:22 UTC, flit commented
> I have addressed the requested changes.

Even better! Thanks 😄

2023-07-31 21:24 UTC, flit approved these changes

2023-07-31 21:24 UTC, flit commented
/azp run

2023-08-05 20:20 UTC, merged