Add STM32H7B0 Target
pyocd/pyOCD pull request #1610
Opened 2023-08-11 04:41 UTC by BrianPugh

Adds the STM32H7B0 target with the following features:
* Extended the flash definition for Bank 1 to 256KB.
* Added the undocumented Bank 2 (256KB).
* Added custom modified flash algorithm for supporting 256KB.

I've tested erasing and flashing >128KB firmware to both Bank 1 and Bank 2 with success.

Builds on-top of #1608, so that should be merged first.

Possible TODOs that I need help on:
1. Maybe detect silicon revision and display appropriate warning if an unknown revision is detected.

2023-08-13 19:21 UTC, flit approved these changes

2023-08-13 19:21 UTC, flit commented on pyocd/target/builtin/__init__.py
> +          'stm32h7b0' : target_STM32H7B0.STM32H7B0,
Would you mind adding xx's to the target name so it becomes `stm32h7b0xx`? (Granted the F051 is not like that, but that's historical…)

2023-08-13 19:22 UTC, flit requested changes
Only change request is the target name.

2023-08-13 20:16 UTC, BrianPugh commented
updated!

2023-08-15 20:00 UTC, flit approved these changes

2023-08-15 20:01 UTC, flit commented
Oops, looks like you'll have to rebase after that previous PR was merged.

2023-08-15 21:48 UTC, BrianPugh commented
rebased; I also made the  `stm32h7b0` -> `stm32h7b0xx` name change everywhere.

2023-08-21 20:13 UTC, flit commented
/azp run

2023-08-29 16:21 UTC, merged