truncated unused bytes of a command buffer.
pyocd/pyOCD pull request #998
Opened 2020-11-09 14:09 UTC by kkitayam

I found that DAP_TRANSFER and DAP_TRANSFER_BLOCK send packets with endpoint size when using CMSIS-DAP v2.
I think that it's better to truncate unused bytes.

2020-11-10 21:45 UTC, flit commented
/morph test

2020-11-12 17:50 UTC, flit commented
/morph test

2020-11-15 16:25 UTC, flit requested changes
The code changes look good. Thanks for the patch!

One request: would you mind adding your copyright below the existing copyright in the license header of `dap_acces_cmsis_dap.py`? Thanks.

2020-11-16 11:14 UTC, tsukimiudon commented
Thank you for your comments.

I am happy to contribute for this great project!
Thanks.

2020-11-16 11:18 UTC, kkitayam commented
Thank you for your comments.

I am happy to contribute for this great project!
Thanks.

2020-11-19 22:06 UTC, flit commented
/morph test

2020-11-27 22:44 UTC, merged